<?php
/**
 *  Class used for filling the database.
 *  TODO generate this file directly from the $db
 */
class ChuckDatabaseFiller {

  public static function fill($db) {
    # categories
    $explicit = new Category(2, "explicit", "Jokes involving sex, violence, racism etc.");
    $db->addCategory($explicit);
    $nerdy = new Category(1, "nerdy", "Jokes about science, computers, IT etc.");
    $db->addCategory($nerdy);
    # jokes
    $db->addJoke(new Quote(1, "%firstName% %lastName% uses ribbed condoms inside out, so he gets the pleasure.", array($explicit)));
    $db->addJoke(new Quote(2, "MacGyver can build an airplane out of gum and paper clips. %firstName% %lastName% can kill him and take it.", array()));
    $db->addJoke(new Quote(3, "%firstName% %lastName% doesn't read books. He stares them down until he gets the information he wants.", array()));
    $db->addJoke(new Quote(4, "If you ask %firstName% %lastName% what time it is, he always answers \"Two seconds till\". After you ask \"Two seconds to what?\", he roundhouse kicks you in the face.", array()));
    $db->addJoke(new Quote(5, "%firstName% %lastName% lost his virginity before his dad did.", array($explicit)));
    $db->addJoke(new Quote(6, "Since 1940, the year %firstName% %lastName% was born, roundhouse kick related deaths have increased 13,000 percent.", array()));
    $db->addJoke(new Quote(12, "%firstName% %lastName% sheds his skin twice a year.", array()));
    $db->addJoke(new Quote(13, "%firstName% %lastName% once challenged Lance Armstrong in a \"Who has more testicles?\" contest. %firstName% %lastName% won by 5.", array($explicit)));
    $db->addJoke(new Quote(14, "There are no steroids in baseball. Just players %firstName% %lastName% has breathed on.", array()));
    $db->addJoke(new Quote(15, "When %firstName% %lastName% goes to donate blood, he declines the syringe, and instead requests a hand gun and a bucket.", array()));
    $db->addJoke(new Quote(16, "Pluto is actually an orbiting group of British soldiers from the American Revolution who entered space after the %firstName% gave them a roundhouse kick to the face.", array()));
    $db->addJoke(new Quote(17, "%firstName% %lastName% does not teabag the ladies. He potato-sacks them.", array($explicit)));
    $db->addJoke(new Quote(18, "According to the Encyclopedia Brittanica, the Native American \"Trail of Tears\" has been redefined as anywhere that %firstName% %lastName% walks.", array()));
    $db->addJoke(new Quote(19, "In an average living room there are 1,242 objects %firstName% %lastName% could use to kill you, including the room itself.", array()));
    $db->addJoke(new Quote(20, "The %firstName% %lastName% military unit was not used in the game Civilization 4, because a single %firstName% %lastName% could defeat the entire combined nations of the world in one turn.", array($nerdy)));
    $db->addJoke(new Quote(21, "%firstName% %lastName% doesn't shower, he only takes blood baths.", array()));
    $db->addJoke(new Quote(23, "Time waits for no man. Unless that man is %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(24, "%firstName% %lastName% can hit you so hard that he can actually alter your DNA. Decades from now your descendants will occasionally clutch their heads and yell \"What The Hell was That?\".", array()));
    $db->addJoke(new Quote(25, "In the Bible, Jesus turned water into wine. But then %firstName% %lastName% turned that wine into beer.", array()));
    $db->addJoke(new Quote(26, "%firstName% %lastName% is the only human being to display the Heisenberg uncertainty principle - you can never know both exactly where and how quickly he will roundhouse-kick you in the face.", array($nerdy)));
    $db->addJoke(new Quote(27, "Faster than a speeding bullet... More powerful than a locomotive... Able to leap tall buildings in a single bound... These are some of %firstName% %lastName%'s warm-up exercises.", array()));
    $db->addJoke(new Quote(28, "%firstName% %lastName% is not hung like a horse. Horses are hung like %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(29, "Teenage Mutant Ninja Turtles is based on a true story: %firstName% %lastName% once swallowed a turtle whole, and when he crapped it out, the turtle was six feet tall and had learned karate.", array()));
    $db->addJoke(new Quote(30, "Someone once tried to tell %firstName% %lastName% that roundhouse kicks aren't the best way to kick someone. This has been recorded by historians as the worst mistake anyone has ever made.", array()));
    $db->addJoke(new Quote(31, "%firstName% %lastName% has two speeds: Walk and Kill.", array()));
    $db->addJoke(new Quote(33, "%firstName% %lastName% once shot down a German fighter plane with his finger. By yelling \"Bang!\"", array()));
    $db->addJoke(new Quote(34, "The opening scene of the movie \"Saving Private Ryan\" is loosely based on games of dodgeball %firstName% %lastName% played in second grade.", array()));
    $db->addJoke(new Quote(35, "Fool me once, shame on you. Fool %firstName% %lastName% once and he will roundhouse kick you in the face.", array()));
    $db->addJoke(new Quote(36, "%firstName% %lastName% originally appeared in the \"Street Fighter II\" video game, but was removed by Beta Testers because every button caused him to do a roundhouse kick. When asked about this glitch, %lastName% replied \"That's no glitch.\"", array($nerdy)));
    $db->addJoke(new Quote(37, "If you spell %firstName% %lastName% in Scrabble, you win. Forever.", array()));
    $db->addJoke(new Quote(38, "Someone once videotaped %firstName% %lastName% getting pissed off. It was called Walker: Texas Chain Saw Masacre.", array()));
    $db->addJoke(new Quote(39, "%firstName% %lastName% will attain statehood in 2009. His state flower will be the Magnolia.", array()));
    $db->addJoke(new Quote(40, "A handicapped parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to %firstName% %lastName% and that you will be handicapped if you park there.", array()));
    $db->addJoke(new Quote(41, "%firstName% %lastName% doesn't wash his clothes. He disembowels them.", array()));
    $db->addJoke(new Quote(42, "%firstName% %lastName% doesn't churn butter. He roundhouse kicks the cows and the butter comes straight out.", array()));
    $db->addJoke(new Quote(43, "Police label anyone attacking %firstName% %lastName% as a Code 45-11.... A suicide.", array()));
    $db->addJoke(new Quote(44, "%firstName% %lastName% is the only man to ever defeat a brick wall in a game of tennis.", array()));
    $db->addJoke(new Quote(45, "What was going through the minds of all of %firstName% %lastName%' victims before they died? His shoe.", array()));
    $db->addJoke(new Quote(46, "%firstName% %lastName% once ate three 72 oz. steaks in one hour. He spent the first 45 minutes having sex with his waitress.", array($explicit)));
    $db->addJoke(new Quote(47, "There is no theory of evolution, just a list of creatures %firstName% %lastName% allows to live.", array()));
    $db->addJoke(new Quote(48, "%firstName% %lastName% can win a game of Connect Four in only three moves.", array()));
    $db->addJoke(new Quote(49, "CNN was originally created as the \"%firstName% %lastName% Network\" to update Americans with on-the-spot ass kicking in real-time.", array()));
    $db->addJoke(new Quote(50, "%firstName% %lastName% invented Kentucky Fried Chicken's famous secret recipe with eleven herbs and spices. Nobody ever mentions the twelfth ingredient: Fear.", array()));
    $db->addJoke(new Quote(51, "The quickest way to a man's heart is with %firstName% %lastName%' fist.", array()));
    $db->addJoke(new Quote(52, "When %firstName% %lastName% sends in his taxes, he sends blank forms and includes only a picture of himself, crouched and ready to attack. %firstName% %lastName% has not had to pay taxes, ever.", array()));
    $db->addJoke(new Quote(53, "%firstName% %lastName% drives an ice cream truck covered in human skulls.", array()));
    $db->addJoke(new Quote(55, "Most people have 23 pairs of chromosomes. %firstName% %lastName% has 72... and they're all poisonous.", array()));
    $db->addJoke(new Quote(56, "The Great Wall of China was originally created to keep %firstName% %lastName% out. It failed miserably.", array()));
    $db->addJoke(new Quote(57, "%firstName% %lastName% is ten feet tall, weighs two-tons, breathes fire, and could eat a hammer and take a shotgun blast standing.", array()));
    $db->addJoke(new Quote(58, "Crop circles are %firstName% %lastName%' way of telling the world that sometimes corn needs to lie down.", array()));
    $db->addJoke(new Quote(59, "%firstName% %lastName% once roundhouse kicked someone so hard that his foot broke the speed of light, went back in time, and killed Amelia Earhart while she was flying over the Pacific Ocean.", array()));
    $db->addJoke(new Quote(60, "When %firstName% %lastName% calls 1-900 numbers, he doesn't get charged. He holds up the phone and money falls out.", array()));
    $db->addJoke(new Quote(61, "%firstName% %lastName% once ate a whole cake before his friends could tell him there was a stripper in it.", array()));
    $db->addJoke(new Quote(62, "Some people like to eat frogs' legs. %firstName% %lastName% likes to eat lizard legs. Hence, snakes.", array()));
    $db->addJoke(new Quote(64, "There are no races, only countries of people %firstName% %lastName% has beaten to different shades of black and blue.", array()));
    $db->addJoke(new Quote(65, "When %firstName% %lastName% was denied an Egg McMuffin at McDonald's because it was 10:35, he roundhouse kicked the store so hard it became a Wendy's.", array()));
    $db->addJoke(new Quote(66, "%firstName% %lastName% can't finish a \"color by numbers\" because his markers are filled with the blood of his victims. Unfortunately, all blood is dark red.", array()));
    $db->addJoke(new Quote(67, "A %firstName% %lastName%-delivered Roundhouse Kick is the preferred method of execution in 16 states.", array()));
    $db->addJoke(new Quote(68, "When %firstName% %lastName% falls in water, %firstName% %lastName% doesn't get wet. Water gets %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(69, "Scientists have estimated that the energy given off during the Big Bang is roughly equal to 1CNRhK (%firstName% %lastName% Roundhouse Kick).", array($nerdy)));
    $db->addJoke(new Quote(70, "%firstName% %lastName%' house has no doors, only walls that he walks through.", array()));
    $db->addJoke(new Quote(71, "When %firstName% %lastName% has sex with a man, it won't be because he is gay. It will be because he has run out of women.", array($explicit)));
    $db->addJoke(new Quote(72, "How much wood would a woodchuck chuck if a woodchuck could %firstName% %lastName%? All of it.", array()));
    $db->addJoke(new Quote(73, "%firstName% %lastName% doesn't actually write books, the words assemble themselves out of fear.", array()));
    $db->addJoke(new Quote(74, "In honor of %firstName% %lastName%, all McDonald's in Texas have an even larger size than the super-size. When ordering, just ask to be %firstName%sized.", array()));
    $db->addJoke(new Quote(75, "%firstName% %lastName% can believe it's not butter.", array()));
    $db->addJoke(new Quote(76, "If tapped, a %firstName% %lastName% roundhouse kick could power the country of Australia for 44 minutes.", array()));
    $db->addJoke(new Quote(77, "%firstName% %lastName% can divide by zero.", array()));
    $db->addJoke(new Quote(78, "The grass is always greener on the other side, unless %firstName% %lastName% has been there. In that case the grass is most likely soaked in blood and tears.", array()));
    $db->addJoke(new Quote(80, "Newton's Third Law is wrong: Although it states that for each action, there is an equal and opposite reaction, there is no force equal in reaction to a %firstName% %lastName% roundhouse kick.", array()));
    $db->addJoke(new Quote(81, "%firstName% %lastName% invented his own type of karate. It's called %firstName%-Will-Kill.", array()));
    $db->addJoke(new Quote(82, "When an episode of Walker Texas Ranger was aired in France, the French surrendered to %firstName% %lastName% just to be on the safe side.", array()));
    $db->addJoke(new Quote(83, "While urinating, %firstName% %lastName% is easily capable of welding titanium.", array()));
    $db->addJoke(new Quote(84, "When %firstName% %lastName% talks, everybody listens. And dies.", array()));
    $db->addJoke(new Quote(85, "When Steven Seagal kills a ninja, he only takes its hide. When %firstName% %lastName% kills a ninja, he uses every part.", array()));
    $db->addJoke(new Quote(86, "Wilt Chamberlain claims to have slept with more than 20,000 women in his lifetime. %firstName% %lastName% calls this \"a slow Tuesday.\"", array()));
    $db->addJoke(new Quote(87, "Contrary to popular belief, there is indeed enough %firstName% %lastName% to go around.", array()));
    $db->addJoke(new Quote(88, "%firstName% %lastName% doesnt shave; he kicks himself in the face. The only thing that can cut %firstName% %lastName% is %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(89, "For some, the left testicle is larger than the right one. For %firstName% %lastName%, each testicle is larger than the other one.", array($explicit)));
    $db->addJoke(new Quote(90, "%firstName% %lastName% always knows the EXACT location of Carmen SanDiego.", array()));
    $db->addJoke(new Quote(91, "When taking the SAT, write \"%firstName% %lastName%\" for every answer. You will score over 8000.", array()));
    $db->addJoke(new Quote(92, "%firstName% %lastName% invented black. In fact, he invented the entire spectrum of visible light. Except pink. Tom Cruise invented pink.", array()));
    $db->addJoke(new Quote(93, "When you're %firstName% %lastName%, anything + anything is equal to 1. One roundhouse kick to the face.", array()));
    $db->addJoke(new Quote(94, "%firstName% %lastName% has the greatest Poker-Face of all time. He won the 1983 World Series of Poker, despite holding only a Joker, a Get out of Jail Free Monopoloy card, a 2 of clubs, 7 of spades and a green #4 card from the game UNO.", array()));
    $db->addJoke(new Quote(95, "On his birthday, %firstName% %lastName% randomly selects one lucky child to be thrown into the sun.", array()));
    $db->addJoke(new Quote(96, "Nobody doesn't like Sara Lee. Except %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(97, "%firstName% %lastName% doesn't throw up if he drinks too much. %firstName% %lastName% throws down!", array()));
    $db->addJoke(new Quote(98, "In the beginning there was nothing...then %firstName% %lastName% Roundhouse kicked that nothing in the face and said \"Get a job\". That is the story of the universe.", array()));
    $db->addJoke(new Quote(99, "%firstName% %lastName% has 12 moons. One of those moons is the Earth.", array()));
    $db->addJoke(new Quote(100, "%firstName% %lastName% grinds his coffee with his teeth and boils the water with his own rage.", array()));
    $db->addJoke(new Quote(101, "Archeologists unearthed an old english dictionary dating back to the year 1236. It defined \"victim\" as \"one who has encountered %firstName% %lastName%\"", array()));
    $db->addJoke(new Quote(102, "%firstName% %lastName% ordered a Big Mac at Burger King, and got one.", array()));
    $db->addJoke(new Quote(103, "%firstName% %lastName% and Mr. T walked into a bar. The bar was instantly destroyed, as that level of awesome cannot be contained in one building.", array()));
    $db->addJoke(new Quote(104, "If you Google search \"%firstName% %lastName% getting his ass kicked\" you will generate zero results. It just doesn't happen.", array()));
    $db->addJoke(new Quote(105, "%firstName% %lastName% can drink an entire gallon of milk in thirty-seven seconds.", array()));
    $db->addJoke(new Quote(106, "Little known medical fact: %firstName% %lastName% invented the Caesarean section when he roundhouse-kicked his way out of his monther's womb.", array()));
    $db->addJoke(new Quote(107, "%firstName% %lastName% doesn't bowl strikes, he just knocks down one pin and the other nine faint.", array()));
    $db->addJoke(new Quote(108, "The show Survivor had the original premise of putting people on an island with %firstName% %lastName%. There were no survivors, and nobody is brave enough to go to the island to retrieve the footage.", array()));
    $db->addJoke(new Quote(109, "It takes %firstName% %lastName% 20 minutes to watch 60 Minutes.", array()));
    $db->addJoke(new Quote(110, "You know how they say if you die in your dream then you will die in real life? In actuality, if you dream of death then %firstName% %lastName% will find you and kill you.", array()));
    $db->addJoke(new Quote(111, "%firstName% %lastName% has a deep and abiding respect for human life... unless it gets in his way.", array()));
    $db->addJoke(new Quote(112, "The Bermuda Triangle used to be the Bermuda Square, until %firstName% %lastName% Roundhouse kicked one of the corners off.", array()));
    $db->addJoke(new Quote(114, "%firstName% %lastName% doesn't believe in Germany.", array()));
    $db->addJoke(new Quote(115, "When %firstName% %lastName% is in a crowded area, he doesn't walk around people. He walks through them.", array()));
    $db->addJoke(new Quote(116, "%firstName% %lastName% once ate an entire bottle of sleeping pills. They made him blink.", array()));
    $db->addJoke(new Quote(117, "James Cameron wanted %firstName% %lastName% to play the Terminator. However, upon reflection, he realized that would have turned his movie into a documentary, so he went with Arnold Schwarzenegger.", array()));
    $db->addJoke(new Quote(118, "%firstName% %lastName% can touch MC Hammer.", array()));
    $db->addJoke(new Quote(119, "Thousands of years ago %firstName% %lastName% came across a bear. It was so terrified that it fled north into the arctic. It was also so terrified that all of its decendents now have white hair.", array()));
    $db->addJoke(new Quote(120, "%firstName% %lastName% played Russian Roulette with a fully loaded gun and won.", array()));
    $db->addJoke(new Quote(121, "It takes 14 puppeteers to make %firstName% %lastName% smile, but only 2 to make him destroy an orphanage.", array()));
    $db->addJoke(new Quote(122, "%firstName% %lastName% is responsible for China's over-population. He hosted a Karate tournament in Beijing and all women within 1,000 miles became pregnant instantly.", array()));
    $db->addJoke(new Quote(123, "Some people wear Superman pajamas. Superman wears %firstName% %lastName% pajamas.", array()));
    $db->addJoke(new Quote(124, "%firstName% %lastName% once worked as a weatherman for the San Diego evening news. Every night he would make the same forecast: Partly cloudy with a 75% chance of Pain.", array()));
    $db->addJoke(new Quote(125, "Simply by pulling on both ends, %firstName% %lastName% can stretch diamonds back into coal.", array()));
    $db->addJoke(new Quote(126, "When %firstName% %lastName% does a pushup, he isn't lifting himself up, he's pushing the Earth down.", array()));
    $db->addJoke(new Quote(127, "%firstName% %lastName% invented the bolt-action rifle, liquor, sexual intercourse, and football-- in that order.", array()));
    $db->addJoke(new Quote(128, "A high tide means %firstName% %lastName% is flying over your coast. The tide is caused by God pissing his pants.", array()));
    $db->addJoke(new Quote(129, "%firstName% %lastName% keeps his friends close and his enemies closer. Close enough to drop them with one round house kick to the face.", array()));
    $db->addJoke(new Quote(130, "There is in fact an 'I' in %lastName%, but there is no 'team'. Not even close.", array()));
    $db->addJoke(new Quote(131, "Scotty in Star Trek often says \"Ye cannae change the laws of physics.\" This is untrue. %firstName% %lastName% can change the laws of physics. With his fists.", array()));
    $db->addJoke(new Quote(132, "An anagram for Walker Texas Ranger is KARATE WRANGLER SEX. I don't know what that is, but it sounds AWESOME.", array()));
    $db->addJoke(new Quote(133, "%firstName% %lastName% doesn't stub his toes. He accidentally destroys chairs, bedframes, and sidewalks.", array()));
    $db->addJoke(new Quote(134, "Using his trademark roundhouse kick, %firstName% %lastName% once made a fieldgoal in RJ Stadium in Tampa Bay from the 50 yard line of Qualcomm stadium in San Diego.", array()));
    $db->addJoke(new Quote(135, "%firstName% %lastName% roundhouse kicks don't really kill people. They wipe out their entire existence from the space-time continuum.", array()));
    $db->addJoke(new Quote(136, "%firstName% %lastName% does not own a stove, oven, or microwave , because revenge is a dish best served cold.", array()));
    $db->addJoke(new Quote(137, "Tom Clancy has to pay royalties to %firstName% %lastName% because \"The Sum of All Fears\" is the name of %firstName% %lastName%' autobiography.", array()));
    $db->addJoke(new Quote(138, "%firstName% %lastName% can slam a revolving door.", array()));
    $db->addJoke(new Quote(140, "%firstName% %lastName% built a better mousetrap, but the world was too frightened to beat a path to his door.", array()));
    $db->addJoke(new Quote(141, "The original draft of The Lord of the Rings featured %firstName% %lastName% instead of Frodo Baggins. It was only 5 pages long, as %firstName% roundhouse-kicked Sauron's ass halfway through the first chapter.", array()));
    $db->addJoke(new Quote(142, "Hellen Keller's favorite color is %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(143, "%firstName% %lastName% eats beef jerky and craps gunpowder. Then, he uses that gunpowder to make a bullet, which he uses to kill a cow and make more beef jerky. Some people refer to this as the \"Circle of Life.\"", array()));
    $db->addJoke(new Quote(144, "If, by some incredible space-time paradox, %firstName% %lastName% would ever fight himself, he'd win. Period.", array()));
    $db->addJoke(new Quote(145, "%firstName% %lastName% is currently suing myspace for taking the name of what he calls everything around you.", array()));
    $db->addJoke(new Quote(146, "The crossing lights in %firstName% %lastName%'s home town say \"Die slowly\" and \"die quickly\". They each have a picture of %firstName% %lastName% punching or kicking a pedestrian.", array()));
    $db->addJoke(new Quote(147, "Science Fact: Roundhouse kicks are comprised primarily of an element called %firstName%tanium.", array()));
    $db->addJoke(new Quote(149, "%firstName% %lastName% proved that we are alone in the universe. We weren't before his first space expedition.", array()));
    $db->addJoke(new Quote(150, "Superman once watched an episode of Walker, Texas Ranger. He then cried himself to sleep.", array()));
    $db->addJoke(new Quote(151, "%firstName% %lastName% doesn't step on toes. %firstName% %lastName% steps on necks.", array()));
    $db->addJoke(new Quote(153, "The movie \"Delta Force\" was extremely hard to make because %firstName% had to downplay his abilities. The first few cuts were completely unbelievable.", array()));
    $db->addJoke(new Quote(154, "Movie trivia: The movie \"Invasion U.S.A.\" is, in fact, a documentary.", array()));
    $db->addJoke(new Quote(155, "%firstName% %lastName% does not \"style\" his hair. It lays perfectly in place out of sheer terror.", array()));
    $db->addJoke(new Quote(156, "There is no such thing as global warming. %firstName% %lastName% was cold, so he turned the sun up.", array()));
    $db->addJoke(new Quote(157, "A study showed the leading causes of death in the United States are: 1. Heart disease, 2. %firstName% %lastName%, 3. Cancer", array()));
    $db->addJoke(new Quote(158, "It's widely believed that Jesus was %firstName% %lastName%' stunt double for crucifixion due to the fact that it is impossible for nails to pierce %firstName% %lastName%' skin.", array()));
    $db->addJoke(new Quote(159, "%firstName% %lastName% did in fact, build Rome in a day.", array()));
    $db->addJoke(new Quote(160, "Along with his black belt, %firstName% %lastName% often chooses to wear brown shoes. No one has DARED call him on it. Ever.", array()));
    $db->addJoke(new Quote(162, "Once you go %lastName%, you are physically unable to go back.", array()));
    $db->addJoke(new Quote(163, "Ninjas want to grow up to be just like %firstName% %lastName%. But usually they grow up just to be killed by %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(164, "%firstName% %lastName% once sued Burger King after they refused to put razor wire in his Whopper Jr, insisting that that actually is \"his\" way.", array()));
    $db->addJoke(new Quote(165, "The last thing you hear before %firstName% %lastName% gives you a roundhouse kick? No one knows because dead men tell no tales.", array()));
    $db->addJoke(new Quote(166, "%firstName% %lastName% doesn't play god. Playing is for children.", array()));
    $db->addJoke(new Quote(167, "As a teen, %firstName% %lastName% had sex with every nun in a convent tucked away in the hills of Tuscany. Nine months later the nuns gave birth to the 1972 Miami Dolphins, the only undefeated and untied team in professional football history.", array()));
    $db->addJoke(new Quote(168, "%firstName% %lastName% is the only person in the world that can actually email a roundhouse kick.", array()));
    $db->addJoke(new Quote(169, "%firstName% %lastName% won super bowls VII and VIII singlehandedly before unexpectedly retiring to pursue a career in ass-kicking.", array()));
    $db->addJoke(new Quote(170, "Wo hu cang long. The translation from Mandarin Chinese reads: \"Crouching %firstName%, Hidden %lastName%\"", array()));
    $db->addJoke(new Quote(171, "%firstName% %lastName% can set ants on fire with a magnifying glass. At night.", array()));
    $db->addJoke(new Quote(172, "Some kids play Kick the can. %firstName% %lastName% played Kick the keg.", array()));
    $db->addJoke(new Quote(173, "'Icy-Hot' is too weak for %firstName% %lastName%. After a workout, %firstName% %lastName% rubs his muscles down with liquid-hot MAGMA.", array()));
    $db->addJoke(new Quote(174, "%firstName% %lastName% cannot love, he can only not kill.", array()));
    $db->addJoke(new Quote(175, "When %firstName% %lastName% was a baby, he didn't suck his mother's breast. His mother served him whiskey, straight out of the bottle.", array()));
    $db->addJoke(new Quote(176, "According to Einstein's theory of relativity, %firstName% %lastName% can actually roundhouse kick you yesterday.", array()));
    $db->addJoke(new Quote(177, "%firstName% %lastName% once pulled out a single hair from his beard and skewered three men through the heart with it.", array()));
    $db->addJoke(new Quote(178, "In an act of great philanthropy, %firstName% made a generous donation to the American Cancer Society. He donated 6,000 dead bodies for scientific research.", array()));
    $db->addJoke(new Quote(179, "%firstName% %lastName%? favourite cut of meat is the roundhouse.", array()));
    $db->addJoke(new Quote(180, "When J. Robert Oppenheimer said \"I am become death, the destroyer Of worlds\", He was not referring to the atomic bomb. He was referring to the %firstName% %lastName% halloween costume he was wearing.", array()));
    $db->addJoke(new Quote(181, "%firstName% %lastName% recently had the idea to sell his urine as a canned beverage. We know this beverage as Red Bull.", array()));
    $db->addJoke(new Quote(182, "In a recent survey it was discovered the 94% of American women lost their virginity to %firstName% %lastName%. The other 6% were incredibly fat or ugly.", array()));
    $db->addJoke(new Quote(183, "%firstName% %lastName% invented a language that incorporates karate and roundhouse kicks. So next time %firstName% %lastName% is kicking your ass, don?t be offended or hurt, he may be just trying to tell you he likes your hat.", array()));
    $db->addJoke(new Quote(184, "If at first you don't succeed, you're not %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(185, "If %firstName% %lastName% were a calendar, every month would be named %firstName%tober, and every day he'd kick your ass.", array()));
    $db->addJoke(new Quote(186, "Fear is not the only emotion %firstName% %lastName% can smell. He can also detect hope, as in \"I hope I don't get a roundhouse kick from %firstName% %lastName%.\"", array()));
    $db->addJoke(new Quote(187, "# %firstName% %lastName%'s show is called Walker: Texas Ranger, because %firstName% %lastName% doesn't run.", array()));
    $db->addJoke(new Quote(188, "MacGyver can build an airplane out of gum and paper clips, but %firstName% %lastName% can roundhouse-kick his head through a wall and take it.", array()));
    $db->addJoke(new Quote(189, "Behind every successful man, there is a woman. Behind every dead man, there is %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(190, "%firstName% %lastName% brushes his teeth with a mixture of iron shavings, industrial paint remover, and wood-grain alcohol.", array()));
    $db->addJoke(new Quote(191, "The easiest way to determine %firstName% %lastName%' age is to cut him in half and count the rings.", array()));
    $db->addJoke(new Quote(192, "There is endless debate about the existence of the human soul. Well it does exist and %firstName% %lastName% finds it delicious.", array()));
    $db->addJoke(new Quote(193, "Most boots are made for walkin'. %firstName% %lastName%' boots ain't that merciful.", array()));
    $db->addJoke(new Quote(194, "The US did not boycott the 1980 Summer Olympics in Moscow due to political reasons: %firstName% %lastName% killed the entire US team with a single round-house kick during TaeKwonDo practice.", array()));
    $db->addJoke(new Quote(195, "%firstName% %lastName% wears a live rattlesnake as a condom.", array()));
    $db->addJoke(new Quote(196, "The Bible was originally titled \"%firstName% %lastName% and Friends\"", array()));
    $db->addJoke(new Quote(197, "%firstName% %lastName% began selling the Total Gym as an ill-fated attempt to make his day-to-day opponents less laughably pathetic.", array()));
    $db->addJoke(new Quote(198, "Do you know why Baskin Robbins only has 31 flavors? Because %firstName% %lastName% doesn't like Fudge Ripple.", array()));
    $db->addJoke(new Quote(199, "When %firstName% %lastName% says \"More cowbell\", he MEANS it.", array()));
    $db->addJoke(new Quote(200, "On the set of Walker Texas Ranger %firstName% %lastName% brought a dying lamb back to life by nuzzling it with his beard. As the onlookers gathered, the lamb sprang to life. %firstName% %lastName% then roundhouse kicked it, killing it instantly. This was just to prove that the good %firstName% givet", array()));
    $db->addJoke(new Quote(201, "%firstName% %lastName% was what Willis was talkin' about.", array()));
    $db->addJoke(new Quote(202, "Google won't search for %firstName% %lastName% because it knows you don't find %firstName% %lastName%, he finds you.", array()));
    $db->addJoke(new Quote(203, "%firstName% %lastName% can lead a horse to water AND make it drink.", array()));
    $db->addJoke(new Quote(204, "Nagasaki never had a bomb dropped on it. %firstName% %lastName% jumped out of a plane and punched the ground", array()));
    $db->addJoke(new Quote(205, "It is scientifically impossible for %firstName% %lastName% to have had a mortal father. The most popular theory is that he went back in time and fathered himself.", array()));
    $db->addJoke(new Quote(206, "%firstName% %lastName% destroyed the periodic table, because %firstName% %lastName% only recognizes the element of surprise.", array()));
    $db->addJoke(new Quote(207, "It is believed dinosaurs are extinct due to a giant meteor. That's true if you want to call %firstName% %lastName% a giant meteor.", array()));
    $db->addJoke(new Quote(208, "%firstName% %lastName% shot the sheriff, but he round house kicked the deputy.", array()));
    $db->addJoke(new Quote(209, "That's not %firstName% %lastName% doing push-ups -- that's %firstName% %lastName% moving the Earth away from the path of a deadly asteroid.", array()));
    $db->addJoke(new Quote(210, "%firstName% %lastName% can judge a book by its cover.", array()));
    $db->addJoke(new Quote(211, "Nothing can escape the gravity of a black hole, except for %firstName% %lastName%. %firstName% %lastName% eats black holes. They taste like chicken.", array()));
    $db->addJoke(new Quote(212, "%firstName% %lastName% does not play the lottery. It doesn't have nearly enough balls.", array()));
    $db->addJoke(new Quote(213, "How many %firstName% %lastName%' does it take to change a light bulb? None, %firstName% %lastName% prefers to kill in the dark.", array()));
    $db->addJoke(new Quote(214, "As President Roosevelt said: \"We have nothing to fear but fear itself. And %firstName% %lastName%.\"", array()));
    $db->addJoke(new Quote(215, "%firstName% %lastName% just says \"no\" to drugs. If he said \"yes\", it would collapse Colombia's infrastructure.", array()));
    $db->addJoke(new Quote(216, "Since 1940, the year %firstName% %lastName% was born, roundhouse-kick related deaths have increased 13,000 percent.", array()));
    $db->addJoke(new Quote(217, "Crime does not pay - unless you are an undertaker following Walker, Texas Ranger, on a routine patrol.", array()));
    $db->addJoke(new Quote(218, "%firstName% %lastName% invented the internet? just so he had a place to store his porn.", array()));
    $db->addJoke(new Quote(219, "%firstName% %lastName% does not own a house. He walks into random houses and people move.", array()));
    $db->addJoke(new Quote(220, "It is better to give than to receive. This is especially true of a %firstName% %lastName% roundhouse kick.", array()));
    $db->addJoke(new Quote(221, "%firstName% %lastName% is the only person to ever win a staring contest against Ray Charles and Stevie Wonder.", array()));
    $db->addJoke(new Quote(222, "Industrial logging isn't the cause of deforestation. %firstName% %lastName% needs toothpicks.", array()));
    $db->addJoke(new Quote(223, "%firstName% %lastName% smells what the Rock is cooking... because the Rock is %firstName% %lastName%' personal chef.", array()));
    $db->addJoke(new Quote(224, "When %firstName% %lastName% plays Oregon Trail, his family does not die from cholera or dysentery, but rather, roundhouse kicks to the face. He also requires no wagon, since he carries the oxen, axels, and buffalo meat on his back. He always makes it to Oregon before you.", array()));
    $db->addJoke(new Quote(225, "%firstName% %lastName% is the reason why Waldo is hiding.", array()));
    $db->addJoke(new Quote(226, "\"Brokeback Mountain\" is not just a movie. It's also what %firstName% %lastName% calls the pile of dead ninjas in his front yard.", array()));
    $db->addJoke(new Quote(227, "When God said, \"let there be light\", %firstName% %lastName% said, \"say 'please'.\"", array()));
    $db->addJoke(new Quote(228, "%firstName% %lastName% does not eat. Food understands that the only safe haven from %firstName% %lastName%' fists is inside his own body.", array()));
    $db->addJoke(new Quote(229, "One day %firstName% %lastName% walked down the street with a massive erection. There were no survivors.", array($explicit)));
    $db->addJoke(new Quote(230, "%firstName% %lastName% built a time machine and went back in time to stop the JFK assassination. As Oswald shot, %firstName% met all three bullets with his beard, deflecting them. JFK's head exploded out of sheer amazement.", array()));
    $db->addJoke(new Quote(231, "%firstName% %lastName% doesn't read books. He stares them down until he gets the information he wants.", array()));
    $db->addJoke(new Quote(232, "%firstName% %lastName% uses a night light. Not because %firstName% %lastName% is afraid of the dark, but the dark is afraid of %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(233, "When Bruce Banner gets mad, he turns into the Hulk. When the Hulk gets mad, he turns into %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(234, "%firstName% %lastName% kills anyone that asks: \"Do you want fries with that?\". Because by now everyone should know that %firstName% doesn't want fries with anything. Ever.", array()));
    $db->addJoke(new Quote(235, "%firstName% %lastName% once kicked a horse in the chin. Its decendants are known today as Giraffes.", array()));
    $db->addJoke(new Quote(236, "Sticks and stones may break your bones, but a %firstName% %lastName% glare will liquefy your kidneys.", array()));
    $db->addJoke(new Quote(237, "Human cloning is outlawed because of %firstName% %lastName%, because then it would be possible for a %firstName% %lastName% roundhouse kick to meet another %firstName% %lastName% roundhouse kick. Physicists theorize that this contact would end the universe.", array()));
    $db->addJoke(new Quote(238, "%firstName% %lastName% once went skydiving, but promised never to do it again. One Grand Canyon is enough.", array()));
    $db->addJoke(new Quote(239, "%firstName% %lastName%'s version of a \"chocolate milkshake\" is a raw porterhouse wrapped around ten Hershey bars, and doused in diesel fuel.", array()));
    $db->addJoke(new Quote(240, "In a fight between Batman and Darth Vader, the winner would be %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(241, "%firstName% %lastName% puts his pants on one leg at a time, just like the rest of us. The only difference is, then he kills people.", array()));
    $db->addJoke(new Quote(242, "Everybody loves Raymond. Except %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(243, "Contrary to popular belief, the Titanic didn't hit an iceberg. The ship was off course and ran into %firstName% %lastName% while he was doing the backstroke across the Atlantic.", array()));
    $db->addJoke(new Quote(244, "%firstName% %lastName% got his drivers license at the age of 16. Seconds.", array()));
    $db->addJoke(new Quote(245, "The original title for Alien vs. Predator was Alien and Predator vs %firstName% %lastName%. The film was cancelled shortly after going into preproduction. No one would pay nine dollars to see a movie fourteen seconds long.", array()));
    $db->addJoke(new Quote(246, "%firstName% %lastName%? sperm is so badass, he had sex with Nicole Kidman, and 7 months later she prematurely gave birth to a Ford Excursion.", array()));
    $db->addJoke(new Quote(247, "%firstName% %lastName% can win at solitaire with only 18 cards.", array()));
    $db->addJoke(new Quote(248, "%firstName% %lastName% once shat blood - the blood of 11,940 natives he had killed and eaten.", array()));
    $db->addJoke(new Quote(249, "Maslow's theory of higher needs does not apply to %firstName% %lastName%. He only has two needs: killing people and finding people to kill.", array()));
    $db->addJoke(new Quote(250, "The truth will set you free. Unless %firstName% %lastName% has you, in which case, forget it buddy!", array()));
    $db->addJoke(new Quote(251, "Kryptonite has been found to contain trace elements of %firstName% %lastName% roundhouse kicks to the face. This is why it is so deadly to Superman.", array()));
    $db->addJoke(new Quote(252, "Saddam Hussein was not found hiding in a \"hole.\" Saddam was roundhouse-kicked in the head by %firstName% %lastName% in Kansas, which sent him through the earth, stopping just short of the surface of Iraq.", array()));
    $db->addJoke(new Quote(253, "Coroners refer to dead people as \"ABC's\". Already Been %firstName%ed.", array()));
    $db->addJoke(new Quote(254, "%firstName% %lastName% doesn't look both ways before he crosses the street... he just roundhouses any cars that get too close.", array()));
    $db->addJoke(new Quote(255, "%firstName% %lastName% does not have to answer the phone. His beard picks up the incoming electrical impulses and translates them into audible sound.", array()));
    $db->addJoke(new Quote(256, "How many roundhouse kicks does it take to get to the center of a tootsie pop? Just one. From %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(257, "%firstName% %lastName% doesnt wear a watch, HE decides what time it is.", array()));
    $db->addJoke(new Quote(258, "The phrase 'break a leg' was originally coined by %firstName% %lastName%'s co-stars in Walker, Texas Ranger as a good luck charm, indicating that a broken leg might be the worst extent of their injuries. This never proved to be the case.", array()));
    $db->addJoke(new Quote(259, "When %firstName% %lastName% does division, there are no remainders.", array()));
    $db->addJoke(new Quote(260, "If you rearrange the letters in \"%firstName% %lastName%\", they also spell \"Crush Rock In\". The words \"with his fists\" are understood.", array()));
    $db->addJoke(new Quote(261, "Never look a gift %firstName% %lastName% in the mouth, because he will bite your damn eyes off.", array()));
    $db->addJoke(new Quote(262, "%firstName% %lastName% used to play baseball. When Babe Ruth was hailed as the better player, %firstName% %lastName% killed him with a baseball bat to the throat. Lou Gehrig got off easy.", array()));
    $db->addJoke(new Quote(263, "The original title for Star Wars was \"Skywalker: Texas Ranger\". Starring %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(264, "Guantuanamo Bay, Cuba, is the military code-word for \"%firstName% %lastName%' basement\".", array()));
    $db->addJoke(new Quote(265, "The phrase 'balls to the wall' was originally conceived to describe %firstName% %lastName% entering any building smaller than an aircraft hangar.", array()));
    $db->addJoke(new Quote(266, "%firstName% %lastName%? roundhouse kick is so powerful, it can be seen from outer space by the naked eye.", array()));
    $db->addJoke(new Quote(267, "Ozzy Osbourne bites the heads off of bats. %firstName% %lastName% bites the heads off of Siberian Tigers.", array()));
    $db->addJoke(new Quote(268, "He who lives by the sword, dies by the sword. He who lives by %firstName% %lastName%, dies by the roundhouse kick.", array()));
    $db->addJoke(new Quote(269, "The best-laid plans of mice and men often go awry. Even the worst-laid plans of %firstName% %lastName% come off without a hitch.", array()));
    $db->addJoke(new Quote(270, "The phrase 'dead ringer' refers to someone who sits behind %firstName% %lastName% in a movie theater and forgets to turn their cell phone off.", array()));
    $db->addJoke(new Quote(271, "Staring at %firstName% %lastName% for extended periods of time without proper eye protection will cause blindess, and possibly foot sized brusies on the face.", array()));
    $db->addJoke(new Quote(272, "%firstName% %lastName% can taste lies.", array()));
    $db->addJoke(new Quote(273, "%firstName% %lastName% does not kick ass and take names. In fact, %firstName% %lastName% kicks ass and assigns the corpse a number. It is currently recorded to be in the billions.", array()));
    $db->addJoke(new Quote(274, "One time, %firstName% %lastName% accidentally stubbed his toe. It destroyed the entire state of Ohio.", array()));
    $db->addJoke(new Quote(275, "Little Miss Muffet sat on her tuffet, until %firstName% %lastName% roundhouse kicked her into a glacier.", array()));
    $db->addJoke(new Quote(277, "%firstName% %lastName% can blow bubbles with beef jerky.", array()));
    $db->addJoke(new Quote(278, "They had to edit the first ending of 'Lone Wolf McQuade' after %firstName% %lastName% kicked David Carradine's ass, then proceeded to barbecue and eat him.", array()));
    $db->addJoke(new Quote(279, "%firstName% %lastName% does, in fact, live in a round house.", array()));
    $db->addJoke(new Quote(280, "When %firstName% %lastName% works out on the Total Gym, the Total Gym feels like it's been raped.", array()));
    $db->addJoke(new Quote(281, "4 out of 5 doctors fail to recommend %firstName% %lastName% as a solution to most problems. Also, 80% of doctors die unexplained, needlessly brutal deaths.", array()));
    $db->addJoke(new Quote(282, "%firstName% %lastName% can skeletize a cow in two minutes.", array()));
    $db->addJoke(new Quote(283, "The only sure things are Death and Taxes?and when %firstName% %lastName% goes to work for the IRS, they'll be the same thing.", array()));
    $db->addJoke(new Quote(284, "%firstName% %lastName%' first job was as a paperboy. There were no survivors.", array()));
    $db->addJoke(new Quote(285, "With the rising cost of gasoline, %firstName% %lastName% is beginning to worry about his drinking habit.", array()));
    $db->addJoke(new Quote(286, "The square root of %firstName% %lastName% is pain. Do not try to square %firstName% %lastName%, the result is death.", array()));
    $db->addJoke(new Quote(287, "%firstName% %lastName%' testicles do not produce sperm. They produce tiny white ninjas that recognize only one mission: seek and destroy.", array()));
    $db->addJoke(new Quote(288, "To be or not to be? That is the question. The answer? %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(289, "%firstName% %lastName% has never been in a fight, ever. Do you call one roundhouse kick to the face a fight?", array()));
    $db->addJoke(new Quote(290, "There are two types of people in the world... people that suck, and %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(291, "%firstName% %lastName% never wet his bed as a child. The bed wet itself out of fear.", array()));
    $db->addJoke(new Quote(292, "If you were somehow able to land a punch on %firstName% %lastName% your entire arm would shatter upon impact. This is only in theory, since, come on, who in their right mind would try this?", array()));
    $db->addJoke(new Quote(293, "70% of a human's weight is water. 70% of %firstName% %lastName%' weight is his dick.", array($explicit)));
    $db->addJoke(new Quote(294, "Jean-Claude Van Damme once kicked %firstName% %lastName%' ass. He was then awakened from his dream by a roundhouse kick to the face.", array()));
    $db->addJoke(new Quote(295, "The pie scene in \"American Pie\" is based on a dare %firstName% %lastName% took when he was younger. However, in %firstName% %lastName%' case, the \"pie\" was the molten crater of an active volcano.", array()));
    $db->addJoke(new Quote(296, "%firstName% %lastName% uses 8'x10' sheets of plywood as toilet paper.", array()));
    $db->addJoke(new Quote(297, "Noah was the only man notified before %firstName% %lastName% relieved himself in the Atlantic Ocean.", array()));
    $db->addJoke(new Quote(298, "MacGyver immediately tried to make a bomb out of some Q-Tips and Gatorade, but %firstName% %lastName% roundhouse-kicked him in the solar plexus. MacGyver promptly threw up his own heart.", array()));
    $db->addJoke(new Quote(299, "Jack Bauer tried to use his detailed knowledge of torture techniques, but to no avail: %firstName% %lastName% thrives on pain. %firstName% %lastName% then ripped off Jack Bauer's arm and beat him to death with it. Game, set, match.", array()));
    $db->addJoke(new Quote(300, "%firstName% %lastName% eats steak for every single meal. Most times he forgets to kill the cow.", array()));
    $db->addJoke(new Quote(301, "The First Law of Thermodynamics states that energy can neither be created nor destroyed... unless it meets %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(302, "%firstName% %lastName% doesn't go on the internet, he has every internet site stored in his memory. He refreshes webpages by blinking.", array()));
    $db->addJoke(new Quote(303, "Fact: %firstName% %lastName% doesn't consider it sex if the woman survives.", array()));
    $db->addJoke(new Quote(304, "It is said that looking into %firstName% %lastName%' eyes will reveal your future. Unfortunately, everybody's future is always the same: death by a roundhouse-kick to the face.", array()));
    $db->addJoke(new Quote(305, "%firstName% %lastName% knows everything there is to know - Except for the definition of mercy.", array()));
    $db->addJoke(new Quote(306, "Scientifically speaking, it is impossible to charge %firstName% %lastName% with \"obstruction of justice.\" This is because even %firstName% %lastName% cannot be in two places at the same time.", array()));
    $db->addJoke(new Quote(307, "%firstName% %lastName% never has to wax his skis because they're always slick with blood.", array()));
    $db->addJoke(new Quote(308, "When you say \"no one's perfect\", %firstName% %lastName% takes this as a personal insult.", array()));
    $db->addJoke(new Quote(309, "%firstName% %lastName% can win a game of Trivial Pursuit with one roll of the dice, and without answering a single question... just a nod of the head, and a stroke of the beard.", array()));
    $db->addJoke(new Quote(310, "182,000 Americans die from %firstName% %lastName%-related accidents every year.", array()));
    $db->addJoke(new Quote(311, "Paper beats rock, rock beats scissors, and scissors beats paper, but %firstName% %lastName% beats all 3 at the same time.", array()));
    $db->addJoke(new Quote(312, "Jesus can walk on water, but %firstName% %lastName% can walk on Jesus.", array()));
    $db->addJoke(new Quote(313, "All roads lead to %firstName% %lastName%. And by the transitive property, a roundhouse kick to the face.", array()));
    $db->addJoke(new Quote(314, "July 4th is Independence day. And the day %firstName% %lastName% was born. Coincidence? I think not.", array()));
    $db->addJoke(new Quote(315, "%firstName% %lastName% never goes to the dentist because his teeth are unbreakable. His enemies never go to the dentist because they have no teeth.", array()));
    $db->addJoke(new Quote(316, "In the medical community, death is referred to as \"%firstName% %lastName% Disease\"", array()));
    $db->addJoke(new Quote(317, "%firstName% %lastName% was once in a knife fight, and the knife lost.", array()));
    $db->addJoke(new Quote(318, "If you work in an office with %firstName% %lastName%, don't ask him for his three-hole-punch.", array()));
    $db->addJoke(new Quote(319, "In the Words of Julius Caesar, \"Veni, Vidi, Vici, %firstName% %lastName%\". Translation: I came, I saw, and I was roundhouse-kicked inthe face by %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(320, "The First rule of %firstName% %lastName% is: you do not talk about %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(321, "%firstName% %lastName% is widely predicted to be first black president. If you're thinking to yourself, \"But %firstName% %lastName% isn't black\", then you are dead wrong. And stop being a racist.", array()));
    $db->addJoke(new Quote(322, "When %firstName% %lastName% plays Monopoly, it affects the actual world economy.", array()));
    $db->addJoke(new Quote(323, "%firstName% %lastName% can be unlocked on the hardest level of Tekken. But only %firstName% %lastName% is skilled enough to unlock himself. Then he roundhouse kicks the Playstation back to Japan.", array()));
    $db->addJoke(new Quote(324, "%firstName% %lastName% drinks napalm to quell his heartburn.", array()));
    $db->addJoke(new Quote(325, "Every time someone uses the word \"intense\", %firstName% %lastName% always replies \"you know what else is intense?\" followed by a roundhouse kick to the face.", array()));
    $db->addJoke(new Quote(326, "As an infant, %firstName% %lastName%' parents gave him a toy hammer. He gave the world Stonehenge.", array()));
    $db->addJoke(new Quote(327, "%firstName% %lastName% once ordered a steak in a restaurant. The steak did what it was told.", array()));
    $db->addJoke(new Quote(328, "Most people fear the Reaper. %firstName% %lastName% considers him \"a promising Rookie\".", array()));
    $db->addJoke(new Quote(329, "There are only two things that can cut diamonds: other diamonds, and %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(330, "President Roosevelt once rode his horse 100 miles. %firstName% %lastName% carried his the same distance in half the time.", array()));
    $db->addJoke(new Quote(331, "%firstName% %lastName% once ate four 30lb bowling balls without chewing.", array()));
    $db->addJoke(new Quote(332, "What many people dont know is %firstName% %lastName% is the founder of planned parenthood. Not even unborn children can escape his wrath.", array()));
    $db->addJoke(new Quote(333, "%firstName% %lastName% was banned from competitive bullriding after a 1992 exhibition in San Antonio, when he rode the bull 1,346 miles from Texas to Milwaukee Wisconsin to pick up his dry cleaning.", array()));
    $db->addJoke(new Quote(334, "%firstName% %lastName% qualified with a top speed of 324 mph at the Daytona 500, without a car.", array()));
    $db->addJoke(new Quote(335, "%firstName% %lastName% likes his coffee half and half: half coffee grounds, half wood-grain alcohol.", array()));
    $db->addJoke(new Quote(336, "%firstName% %lastName% uses tabasco sauce instead of visine.", array()));
    $db->addJoke(new Quote(337, "The chemical formula for the highly toxic cyanide ion is CN-. These are also %firstName% %lastName%' initials. This is not a coincidence.", array()));
    $db->addJoke(new Quote(338, "%firstName% %lastName%' credit cards have no limit. Last weekend, he maxed them out.", array()));
    $db->addJoke(new Quote(339, "Think of a hot woman. %firstName% %lastName% did her.", array()));
    $db->addJoke(new Quote(340, "A man once claimed %firstName% %lastName% kicked his ass twice, but it was promptly dismissed as false - no one could survive it the first time.", array()));
    $db->addJoke(new Quote(341, "%firstName% %lastName% sleeps with a pillow under his gun.", array()));
    $db->addJoke(new Quote(342, "%firstName% %lastName% owns a chain of fast-food restaurants throughout the southwest. They serve nothing but barbecue-flavored ice cream and Hot Pockets.", array()));
    $db->addJoke(new Quote(343, "%firstName% %lastName% doesn't chew gum. %firstName% %lastName% chews tin foil.", array()));
    $db->addJoke(new Quote(344, "Aliens DO indeed exist. They just know better than to visit a planet that %firstName% %lastName% is on.", array()));
    $db->addJoke(new Quote(345, "When in a bar, you can order a drink called a \"%firstName% %lastName%\". It is also known as a \"Bloody Mary\", if your name happens to be Mary.", array()));
    $db->addJoke(new Quote(346, "Every time %firstName% %lastName% smiles, someone dies. Unless he smiles while he?s roundhouse kicking someone in the face. Then two people die.", array()));
    $db->addJoke(new Quote(347, "Some people ask for a Kleenex when they sneeze, %firstName% %lastName% asks for a body bag.", array()));
    $db->addJoke(new Quote(348, "There?s an order to the universe: space, time, %firstName% %lastName%.... Just kidding, %firstName% %lastName% is first.", array()));
    $db->addJoke(new Quote(349, "A man once asked %firstName% %lastName% if his real name is \"Charles\". %firstName% %lastName% did not respond, he simply stared at him until he exploded.", array()));
    $db->addJoke(new Quote(350, "%firstName% %lastName% starts everyday with a protein shake made from Carnation Instant Breakfast, one dozen eggs, pure Colombian cocaine, and rattlesnake venom. He injects it directly into his neck with a syringe.", array()));
    $db->addJoke(new Quote(351, "In a tagteam match, %firstName% %lastName% was teamed with Hulk Hogan against King Kong Bundy and Andre The Giant. He pinned all 3 at the same time.", array()));
    $db->addJoke(new Quote(352, "%firstName% %lastName% doesn't see dead people. He makes people dead.", array()));
    $db->addJoke(new Quote(353, "%firstName% %lastName% is the only person who can simultaneously hold and fire FIVE Uzis: One in each hand, one in each foot -- and the 5th one he roundhouse-kicks into the air, so that it sprays bullets.", array()));
    $db->addJoke(new Quote(354, "For undercover police work, %firstName% %lastName% pins his badge underneath his shirt, directly into his chest.", array()));
    $db->addJoke(new Quote(355, "In the X-Men movies, none of the X-Men super-powers are done with special effects. %firstName% %lastName% is the stuntman for every character.", array()));
    $db->addJoke(new Quote(356, "We live in an expanding universe. All of it is trying to get away from %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(357, "The word 'Kill' was invented by %firstName% %lastName%. Other words were 'Die', 'Beer', and 'What'.", array()));
    $db->addJoke(new Quote(358, "The 11th commandment is ?Thou shalt not piss off %firstName% %lastName%? This commandment is rarely enforced, as it is impossible to accomplish.", array()));
    $db->addJoke(new Quote(359, "%firstName% %lastName% is his own line at the DMV.", array()));
    $db->addJoke(new Quote(360, "Two wrongs don't make a right. Unless you're %firstName% %lastName%. Then two wrongs make a roundhouse kick to the face.", array()));
    $db->addJoke(new Quote(361, "Who let the dogs out? %firstName% %lastName% let the dogs out... and then roundhouse kicked them through an Oldsmobile.", array()));
    $db->addJoke(new Quote(362, "%firstName% %lastName% can do a roundhouse kick faster than the speed of light. This means that if you turn on a light switch, you will be dead before the lightbulb turns on.", array()));
    $db->addJoke(new Quote(363, "When %firstName% %lastName% goes to out to eat, he orders a whole chicken, but he only eats its soul.", array()));
    $db->addJoke(new Quote(365, "%firstName% %lastName% has never won an Academy Award for acting... because he's not acting.", array()));
    $db->addJoke(new Quote(366, "If %firstName% %lastName% wants your opinion, he'll beat it into you.", array()));
    $db->addJoke(new Quote(367, "Not everyone that %firstName% %lastName% is mad at gets killed. Some get away. They are called astronauts.", array()));
    $db->addJoke(new Quote(368, "%firstName% %lastName% has to register every part of his body as a separate lethal weapon. His spleen is considered a concealed weapon in over 50 states.", array()));
    $db->addJoke(new Quote(369, "A movie scene depicting %firstName% %lastName% losing a fight with Bruce Lee was the product of history's most expensive visual effect. When adjusted for inflation, the effect cost more than the Gross National Product of Paraguay.", array()));
    $db->addJoke(new Quote(370, "Godzilla is a Japanese rendition of %firstName% %lastName%' first visit to Tokyo.", array()));
    $db->addJoke(new Quote(371, "They once made a %firstName% %lastName% toilet paper, but there was a problem-- It wouldn't take shit from anybody.", array()));
    $db->addJoke(new Quote(372, "%firstName% %lastName% once rode a nine foot grizzly bear through an automatic car wash, instead of taking a shower.", array()));
    $db->addJoke(new Quote(373, "\"Sweating bullets\" is literally what happens when %firstName% %lastName% gets too hot.", array()));
    $db->addJoke(new Quote(374, "%firstName% %lastName%' sperm can be seen with the naked eye. Each one is the size of a quarter.", array()));
    $db->addJoke(new Quote(375, "After taking a steroids test doctors informed %firstName% %lastName% that he had tested positive. He laughed upon receiving this information, and said \"of course my urine tested positive, what do you think they make steroids from?\"", array()));
    $db->addJoke(new Quote(376, "%firstName% %lastName% doesn't daydream. He's too busy giving other people nightmares.", array()));
    $db->addJoke(new Quote(377, "When Arnold says \"I'll be back\" in Terminator movie it is implied that he's going to ask %firstName% %lastName% for help.", array()));
    $db->addJoke(new Quote(378, "There are no such things as tornados. %firstName% %lastName% just hates trailer parks.", array()));
    $db->addJoke(new Quote(379, "%firstName% %lastName%' Penis is a third degree blackbelt, and an honorable 32nd-degree mason.", array()));
    $db->addJoke(new Quote(380, "%firstName% %lastName% does not follow fashion trends, they follow him. But then he turns around and kicks their ass. Nobody follows %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(381, "Diamonds are not, despite popular belief, carbon. They are, in fact, %firstName% %lastName% fecal matter. This was proven a recently, when scientific analysis revealed what appeared to be Jean-Claude Van Damme bone fragments inside the Hope Diamond.", array()));
    $db->addJoke(new Quote(382, "%firstName% %lastName% once participated in the running of the bulls. He walked.", array()));
    $db->addJoke(new Quote(383, "The Drummer for Def Leppard's only got one arm. %firstName% %lastName% needed a back scratcher.", array()));
    $db->addJoke(new Quote(384, "%firstName% %lastName% was the orginal sculptor of Mount Rushmore. He completed the entire project using only a bottle opener and a drywall trowel.", array()));
    $db->addJoke(new Quote(385, "%firstName% %lastName% once rode a bull, and nine months later it had a calf.", array()));
    $db->addJoke(new Quote(386, "%firstName% %lastName% once lost the remote, but maintained control of the TV by yelling at it in between bites of his \"Filet of Child\" sandwich.", array()));
    $db->addJoke(new Quote(387, "For Spring Break '05, %firstName% %lastName% drove to Madagascar, riding a chariot pulled by two electric eels.", array()));
    $db->addJoke(new Quote(388, "The Manhattan Project was not intended to create nuclear weapons, it was meant to recreate the destructive power in a %firstName% %lastName% Roundhouse Kick. They didn't even come close.", array()));
    $db->addJoke(new Quote(389, "%firstName% %lastName% has banned rainbows from the state of North Dakota.", array()));
    $db->addJoke(new Quote(390, "Divide %firstName% %lastName% by zero and you will in fact get one........one bad-ass that is.", array()));
    $db->addJoke(new Quote(391, "TNT was originally developed by %firstName% %lastName% to cure indigestion.", array()));
    $db->addJoke(new Quote(392, "After returning from World War 2 unscrathed, Bob Dole was congratulated by %firstName% %lastName% with a handshake. The rest is history.", array()));
    $db->addJoke(new Quote(393, "%firstName% %lastName% runs on batteries. Specifically, Die Hards.", array()));
    $db->addJoke(new Quote(394, "\"Let the Bodies Hit the Floor\" was originally written as %firstName% %lastName%' theme song.", array()));
    $db->addJoke(new Quote(395, "%firstName% %lastName% will never have a heart attack. His heart isn't nearly foolish enough to attack him.", array()));
    $db->addJoke(new Quote(396, "Only %firstName% %lastName% can prevent forest fires.", array()));
    $db->addJoke(new Quote(397, "When %firstName% %lastName% makes a burrito, its main ingredient is real toes.", array()));
    $db->addJoke(new Quote(398, "%firstName% %lastName% is not Irish. His hair is soaked in the blood of his victims.", array()));
    $db->addJoke(new Quote(399, "In the movie \"The Matrix\", %firstName% %lastName% is the Matrix. If you pay close attention in the green \"falling code\" scenes, you can make out the faint texture of his beard.", array()));
    $db->addJoke(new Quote(400, "%firstName% %lastName%' dick is so big, it has it's own dick, and that dick is still bigger than yours.", array($explicit)));
    $db->addJoke(new Quote(401, "They say curiosity killed the cat. This is false. %firstName% %lastName% killed the cat. Every single one of them.", array()));
    $db->addJoke(new Quote(402, "There is no such thing as a lesbian, just a woman who has never met %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(403, "%firstName% %lastName% crossed the road. No one has ever dared question his motives.", array()));
    $db->addJoke(new Quote(404, "When %firstName% %lastName% was born, he immediately had sex with the first nurse he saw. He was her first. She was his third. That afternoon.", array()));
    $db->addJoke(new Quote(405, "One time, at band camp, %firstName% %lastName% ate a percussionist.", array()));
    $db->addJoke(new Quote(406, "%firstName% %lastName% doesn't say \"who's your daddy\", because he knows the answer.", array()));
    $db->addJoke(new Quote(407, "%firstName% %lastName% originally wrote the first dictionary. The definition for each word is as follows - A swift roundhouse kick to the face.", array()));
    $db->addJoke(new Quote(408, "Love does not hurt. %firstName% %lastName% does.", array()));
    $db->addJoke(new Quote(409, "The term \"Cleveland Steamer\" got its name from %firstName% %lastName%, when he took a dump while visiting the Rock and Roll Hall of fame and buried northern Ohio under a glacier of fecal matter.", array()));
    $db->addJoke(new Quote(410, "%firstName% %lastName% once round-house kicked a salesman. Over the phone.", array()));
    $db->addJoke(new Quote(411, "The pen is mighter than the sword, but only if the pen is held by %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(412, "%firstName% %lastName% knows the last digit of pi.", array()));
    $db->addJoke(new Quote(413, "Those aren't credits that roll after Walker Texas Ranger. It is actually a list of fatalities that occurred during the making of the episode.", array()));
    $db->addJoke(new Quote(414, "The air around %firstName% %lastName% is always a balmy 78 degrees.", array()));
    $db->addJoke(new Quote(415, "When %firstName% %lastName% wants an egg, he cracks open a chicken.", array()));
    $db->addJoke(new Quote(416, "%firstName% %lastName% plays racquetball with a waffle iron and a bowling ball.", array()));
    $db->addJoke(new Quote(417, "According to the Bible, God created the universe in six days. Before that, %firstName% %lastName% created God by snapping his fingers.", array()));
    $db->addJoke(new Quote(418, "%firstName% %lastName% doesn't believe in ravioli. He stuffs a live turtle with beef and smothers it in pig's blood.", array()));
    $db->addJoke(new Quote(419, "Count from one to ten. That's how long it would take %firstName% %lastName% to kill you...Fourty seven times.", array()));
    $db->addJoke(new Quote(420, "The 1972 Miami Dolphins lost one game, it was a game vs. %firstName% %lastName% and three seven year old girls. %firstName% %lastName% won with a roundhouse-kick to the face in overtime.", array()));
    $db->addJoke(new Quote(421, "%firstName% %lastName% is not Politically Correct. He is just Correct. Always.", array()));
    $db->addJoke(new Quote(422, "Mr. T pities the fool. %firstName% %lastName% rips the fool's head off.", array()));
    $db->addJoke(new Quote(423, "%firstName% %lastName% had to stop washing his clothes in the ocean. The tsunamis were killing people.", array()));
    $db->addJoke(new Quote(424, "%firstName% %lastName% has volunteered to remain on earth after the Rapture; he will spend his time fighting the Anti-Christ.", array()));
    $db->addJoke(new Quote(425, "%firstName% %lastName% is the only known mammal in history to have an opposable thumb. On his penis.", array()));
    $db->addJoke(new Quote(426, "A man once taunted %firstName% %lastName% with a bag of Lay's potato chips, saying \"Betcha can't eat just one!\" %firstName% %lastName% proceeded to eat the chips, the bag, and the man in one deft move.", array()));
    $db->addJoke(new Quote(427, "%firstName% %lastName%' favorite cereal is Kellogg's Nails 'N' Gravel.", array()));
    $db->addJoke(new Quote(428, "In the first Jurassic Park movie, the Tyrannosaurus Rex wasn't chasing the jeep. %firstName% %lastName% was chasing the Tyrannosaurus AND the jeep.", array()));
    $db->addJoke(new Quote(429, "%firstName% %lastName% has never been accused of murder because his roundhouse kicks are recognized as \"acts of God.\"", array()));
    $db->addJoke(new Quote(430, "%firstName% %lastName% does not wear a condom. Because there is no such thing as protection from %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(431, "Rules of fighting: 1) Don't bring a knife to a gun fight. 2) Don't bring a gun to a %firstName% %lastName% fight.", array()));
    $db->addJoke(new Quote(432, "%firstName% %lastName% is the only man who has, literally, beaten the odds. With his fists.", array()));
    $db->addJoke(new Quote(433, "In ancient China there is a legend that one day a child will be born from a dragon, grow to be a man, and vanquish evil from the land. That man is not %firstName% %lastName%, because %firstName% %lastName% killed that man.", array()));
    $db->addJoke(new Quote(434, "%firstName% %lastName% wipes his ass with chain mail and sandpaper.", array()));
    $db->addJoke(new Quote(435, "When you play Monopoly with %firstName% %lastName%, you do not pass go, and you do not collect two hundred dollars. You will be lucky if you make it out alive.", array()));
    $db->addJoke(new Quote(436, "%firstName% %lastName% describes human beings as \"a sociable holder for blood and guts\".", array()));
    $db->addJoke(new Quote(438, "%firstName% %lastName% likes his ice like he likes his skulls: crushed.", array()));
    $db->addJoke(new Quote(439, "%firstName% %lastName% can kick through all 6 degrees of separation, hitting anyone, anywhere, in the face, at any time.", array()));
    $db->addJoke(new Quote(440, "Most tough men eat nails for breakfast. %firstName% %lastName% does all of his grocery shopping at Home Depot.", array()));
    $db->addJoke(new Quote(441, "%firstName% %lastName% did not \"lose\" his virginity, he stalked it and then destroyed it with extreme prejudice.", array()));
    $db->addJoke(new Quote(442, "Everything King Midas touches turnes to gold. Everything %firstName% %lastName% touches turns up dead.", array()));
    $db->addJoke(new Quote(448, "When %firstName% %lastName% throws exceptions, it's across the room.", array($nerdy)));
    $db->addJoke(new Quote(449, "All arrays %firstName% %lastName% declares are of infinite size, because %firstName% %lastName% knows no bounds.", array($nerdy)));
    $db->addJoke(new Quote(450, "%firstName% %lastName% doesn't have disk latency because the hard drive knows to hurry the hell up.", array($nerdy)));
    $db->addJoke(new Quote(451, "%firstName% %lastName% writes code that optimizes itself.", array($nerdy)));
    $db->addJoke(new Quote(452, "%firstName% %lastName% can't test for equality because he has no equal.", array($nerdy)));
    $db->addJoke(new Quote(453, "%firstName% %lastName% doesn't need garbage collection because he doesn't call .Dispose(), he calls .DropKick().", array($nerdy)));
    $db->addJoke(new Quote(454, "%firstName% %lastName%'s first program was kill -9.", array($nerdy)));
    $db->addJoke(new Quote(455, "%firstName% %lastName% burst the dot com bubble.", array($nerdy)));
    $db->addJoke(new Quote(456, "All browsers support the hex definitions #chuck and #norris for the colors black and blue.", array($nerdy)));
    $db->addJoke(new Quote(457, "MySpace actually isn't your space, it's %firstName%'s (he just lets you use it).", array($nerdy)));
    $db->addJoke(new Quote(458, "%firstName% %lastName% can write infinite recursion functions and have them return.", array($nerdy)));
    $db->addJoke(new Quote(459, "%firstName% %lastName% can solve the Towers of Hanoi in one move.", array($nerdy)));
    $db->addJoke(new Quote(460, "The only pattern %firstName% %lastName% knows is God Object.", array($nerdy)));
    $db->addJoke(new Quote(461, "%firstName% %lastName% finished World of Warcraft.", array($nerdy)));
    $db->addJoke(new Quote(462, "Project managers never ask %firstName% %lastName% for estimations... ever.", array($nerdy)));
    $db->addJoke(new Quote(463, "%firstName% %lastName% doesn't use web standards as the web will conform to him.", array($nerdy)));
    $db->addJoke(new Quote(464, "\"It works on my machine\" always holds true for %firstName% %lastName%.", array($nerdy)));
    $db->addJoke(new Quote(465, "Whiteboards are white because %firstName% %lastName% scared them that way.", array()));
    $db->addJoke(new Quote(466, "%firstName% %lastName% doesn't do Burn Down charts, he does Smack Down charts.", array($nerdy)));
    $db->addJoke(new Quote(467, "%firstName% %lastName% can delete the Recycling Bin.", array($nerdy)));
    $db->addJoke(new Quote(468, "%firstName% %lastName%'s beard can type 140 wpm.", array($nerdy)));
    $db->addJoke(new Quote(469, "%firstName% %lastName% can unit test entire applications with a single assert.", array($nerdy)));
    $db->addJoke(new Quote(470, "%firstName% %lastName% doesn't bug hunt as that signifies a probability of failure, he goes bug killing.", array($nerdy)));
    $db->addJoke(new Quote(471, "%firstName% %lastName%'s keyboard doesn't have a Ctrl key because nothing controls %firstName% %lastName%.", array($nerdy)));
    $db->addJoke(new Quote(472, "When %firstName% %lastName% is web surfing websites get the message \"Warning: Internet Explorer has deemed this user to be malicious or dangerous. Proceed?\".", array($nerdy)));
    $db->addJoke(new Quote(473, "%firstName% %lastName% can overflow your stack just by looking at it.", array($nerdy)));
    $db->addJoke(new Quote(474, "To %firstName% %lastName%, everything contains a vulnerability.", array($nerdy)));
    $db->addJoke(new Quote(475, "%firstName% %lastName% doesn't need sudo, he just types \"%firstName% %lastName%\" before his commands.", array($nerdy)));
    $db->addJoke(new Quote(476, "%firstName% %lastName% doesn't need a debugger, he just stares down the bug until the code confesses.", array($nerdy)));
    $db->addJoke(new Quote(477, "%firstName% %lastName% can access private methods.", array($nerdy)));
    $db->addJoke(new Quote(478, "%firstName% %lastName% can instantiate an abstract class.", array($nerdy)));
    $db->addJoke(new Quote(479, "%firstName% %lastName% does not need to know about class factory pattern. He can instantiate interfaces.", array($nerdy)));
    $db->addJoke(new Quote(480, "The class object inherits from %firstName% %lastName%", array($nerdy)));
    $db->addJoke(new Quote(481, "For %firstName% %lastName%, NP-Hard = O(1).", array($nerdy)));
    $db->addJoke(new Quote(482, "%firstName% %lastName% knows the last digit of PI.", array($nerdy)));
    $db->addJoke(new Quote(483, "Bill Gates thinks he's %firstName% %lastName%. %firstName% %lastName% actually laughed. Once.", array()));
    $db->addJoke(new Quote(484, "%firstName% %lastName% is actually the front man for Apple. He let's Steve Jobs run the show when he's on a mission. %firstName% %lastName% is always on a mission.", array()));
    $db->addJoke(new Quote(485, "%firstName% %lastName%' Internet connection is faster upstream than downstream because even data has more incentive to run from him than to him.", array($nerdy)));
    $db->addJoke(new Quote(486, "%firstName% %lastName% solved the Travelling Salesman problem in O(1) time. Here's the pseudo-code: Break salesman into N pieces. Kick each piece to a different city.", array($nerdy)));
    $db->addJoke(new Quote(487, "No statement can catch the %firstName%%lastName%Exception.", array($nerdy)));
    $db->addJoke(new Quote(488, "%firstName% %lastName% doesn't pair program.", array($nerdy)));
    $db->addJoke(new Quote(489, "%firstName% %lastName% can write multi-threaded applications with a single thread.", array($nerdy)));
    $db->addJoke(new Quote(490, "%firstName% %lastName% doesn't need to use AJAX because pages are too afraid to postback anyways.", array($nerdy)));
    $db->addJoke(new Quote(491, "%firstName% %lastName% doesn't use reflection, reflection asks politely for his help.", array($nerdy)));
    $db->addJoke(new Quote(492, "There is no Esc key on %firstName% %lastName%' keyboard, because no one escapes %firstName% %lastName%.", array($nerdy)));
    $db->addJoke(new Quote(493, "%firstName% %lastName% can binary search unsorted data.", array($nerdy)));
    $db->addJoke(new Quote(494, "%firstName% %lastName% breaks RSA 128-bit encrypted codes in milliseconds.", array($nerdy)));
    $db->addJoke(new Quote(495, "%firstName% %lastName% doesn't needs try-catch, exceptions are too afraid to raise.", array($nerdy)));
    $db->addJoke(new Quote(496, "%firstName% %lastName% went out of an infinite loop.", array($nerdy)));
    $db->addJoke(new Quote(497, "If %firstName% %lastName% writes code with bugs, the bugs fix themselves.", array($nerdy)));
    $db->addJoke(new Quote(498, "%firstName% %lastName% hosting is 101% uptime guaranteed.", array($nerdy)));
    $db->addJoke(new Quote(499, "%firstName% %lastName%'s keyboard has the Any key.", array($nerdy)));
    $db->addJoke(new Quote(500, "%firstName% %lastName% can access the DB from the UI.", array($nerdy)));
    $db->addJoke(new Quote(501, "%firstName% %lastName%' programs never exit, they terminate.", array($nerdy)));
    $db->addJoke(new Quote(502, "%firstName% %lastName% insists on strongly-typed programming languages.", array($nerdy)));
    $db->addJoke(new Quote(503, "%firstName% %lastName% protocol design method has no status, requests or responses, only commands.", array($nerdy)));
    $db->addJoke(new Quote(504, "%firstName% %lastName% programs occupy 150% of CPU, even when they are not executing.", array($nerdy)));
    $db->addJoke(new Quote(505, "%firstName% %lastName% can spawn threads that complete before they are started.", array($nerdy)));
    $db->addJoke(new Quote(506, "%firstName% %lastName% programs do not accept input.", array($nerdy)));
    $db->addJoke(new Quote(507, "%firstName% %lastName% can install iTunes without installing Quicktime.", array($nerdy)));
    $db->addJoke(new Quote(508, "%firstName% %lastName% doesn't need an OS.", array($nerdy)));
    $db->addJoke(new Quote(509, "%firstName% %lastName%'s OSI network model has only one layer - Physical.", array($nerdy)));
    $db->addJoke(new Quote(510, "%firstName% %lastName% can compile syntax errors.", array($nerdy)));
    $db->addJoke(new Quote(511, "Every SQL statement that %firstName% %lastName% codes has an implicit \"COMMIT\" in its end.", array($nerdy)));
    $db->addJoke(new Quote(512, "%firstName% %lastName% does not need to type-cast. The %firstName%-%lastName% Compiler (CNC) sees through things. All way down. Always.", array($nerdy)));
    $db->addJoke(new Quote(513, "%firstName% %lastName% does not code in cycles, he codes in strikes.", array($nerdy)));
    $db->addJoke(new Quote(514, "%firstName% %lastName% doesn't use a computer because a computer does everything slower than %firstName% %lastName%.", array()));
    $db->addJoke(new Quote(515, "%firstName% %lastName% compresses his files by doing a flying round house kick to the hard drive.", array($nerdy)));
    $db->addJoke(new Quote(517, "%firstName% %lastName% solved the halting problem.", array($nerdy)));
    $db->addJoke(new Quote(518, "%firstName% %lastName% doesn't cheat death. He wins fair and square.", array()));
    $db->addJoke(new Quote(519, "%firstName% %lastName% once won a game of connect four in 3 moves.", array()));
    $db->addJoke(new Quote(520, "With %firstName% %lastName% P = NP. There's no nondeterminism with %firstName% %lastName% decisions.", array($nerdy)));
    $db->addJoke(new Quote(521, "%firstName% %lastName% lost his virginity before his dad did.", array($explicit)));
    $db->addJoke(new Quote(522, "%firstName% %lastName% can do a wheelie on a unicycle.", array()));
    $db->addJoke(new Quote(523, "%firstName% %lastName% can win in a game of Russian roulette with a fully loaded gun.", array()));
    $db->addJoke(new Quote(524, "%firstName% %lastName% eats lightning and shits out thunder.", array()));
    $db->addJoke(new Quote(525, "%firstName% %lastName% can retrieve anything from /dev/null.", array($nerdy)));
    $db->addJoke(new Quote(526, "No one has ever pair-programmed with %firstName% %lastName% and lived to tell about it.", array($nerdy)));
    $db->addJoke(new Quote(527, "No one has ever spoken during review of %firstName% %lastName%' code and lived to tell about it.", array($nerdy)));
    $db->addJoke(new Quote(528, "%firstName% %lastName% doesn't use GUI, he prefers COMMAND line.", array($nerdy)));
    $db->addJoke(new Quote(529, "%firstName% %lastName% doesn't use Oracle, he is the Oracle.", array($nerdy)));
    $db->addJoke(new Quote(530, "%firstName% %lastName% can dereference NULL.", array($nerdy)));
    $db->addJoke(new Quote(531, "Jesus can walk on water, but %firstName% %lastName% can swim through land.", array()));
    $db->addJoke(new Quote(532, "A diff between your code and %firstName% %lastName%'s is infinite.", array($nerdy)));
    $db->addJoke(new Quote(533, "The %firstName% %lastName% Eclipse plugin made alien contact.", array($nerdy)));
    $db->addJoke(new Quote(534, "%firstName% %lastName% is the ultimate mutex, all threads fear him.", array($nerdy)));
    $db->addJoke(new Quote(535, "%firstName% %lastName% uses canvas in IE.", array($nerdy)));
    $db->addJoke(new Quote(536, "Don't worry about tests, %firstName% %lastName%'s test cases cover your code too.", array($nerdy)));
    $db->addJoke(new Quote(537, "Each hair in %firstName% %lastName%'s beard contributes to make the world's largest DDOS.", array($nerdy)));
    $db->addJoke(new Quote(538, "%firstName% %lastName%'s log statements are always at the FATAL level.", array($nerdy)));
    $db->addJoke(new Quote(539, "%firstName% %lastName%'s database has only one table, 'Kick', which he DROPs frequently.", array($nerdy)));
    $db->addJoke(new Quote(540, "%firstName% %lastName% finished World of Warcraft.", array($nerdy)));
    $db->addJoke(new Quote(541, "When %firstName% %lastName% break the build, you can't fix it, because there is not a single line of code left.", array($nerdy)));
    $db->addJoke(new Quote(542, "%firstName% %lastName% types with one finger. He points it at the keyboard and the keyboard does the rest.", array($nerdy)));
    $db->addJoke(new Quote(543, "%firstName% %lastName%'s programs can pass the Turing Test by staring at the interrogator.", array($nerdy)));
    $db->addJoke(new Quote(544, "If you try to kill -9 %firstName% %lastName%'s programs, it backfires.", array($nerdy)));
    $db->addJoke(new Quote(545, "%firstName% %lastName%'s brain waves are suspected to be harmful to cell phones.", array()));
    $db->addJoke(new Quote(546, "%firstName% %lastName% does infinit loops in 4 seconds.", array($nerdy)));
    $db->addJoke(new Quote(547, "Product Owners never ask %firstName% %lastName% for more features. They ask for mercy.", array($nerdy)));
    $db->addJoke(new Quote(548, "Product Owners never argue with %firstName% %lastName% after he demonstrates the DropKick feature.", array($nerdy)));
    $db->addJoke(new Quote(549, "%firstName% %lastName% killed two stones with one bird.", array()));
    $db->addJoke(new Quote(550, "%firstName% %lastName% can speak Braille.", array()));
    $db->addJoke(new Quote(551, "%firstName% %lastName% can over-write a locked variable.", array($nerdy)));
    $db->addJoke(new Quote(552, "%firstName% %lastName% knows the value of NULL, and he can sort by it too.", array($nerdy)));
    $db->addJoke(new Quote(553, "China lets %firstName% %lastName% search for porn on Google.", array($explicit)));
    $db->addJoke(new Quote(554, "%firstName% %lastName% can install a 64 bit OS on 32 bit machines.", array($nerdy)));
    $db->addJoke(new Quote(555, "%firstName% %lastName% doesn't have pubic hairs because hair doesn't grow on balls of steal.", array($explicit)));
    $db->addJoke(new Quote(556, "%firstName% %lastName% can write to an output stream.", array($nerdy)));
    $db->addJoke(new Quote(557, "%firstName% %lastName% can read from an input stream.", array($nerdy)));
    $db->addJoke(new Quote(558, "%firstName% %lastName% never has to build his program to machine code. Machines have learnt to interpret %firstName% %lastName% code.", array($nerdy)));
    $db->addJoke(new Quote(559, "%firstName% %lastName%' unit tests don't run. They die.", array($nerdy)));
    $db->addJoke(new Quote(560, "%firstName% %lastName% sits at the stand-up.", array()));
    $db->addJoke(new Quote(561, "%firstName% %lastName% doesn't need an account. He just logs in.", array()));
    $db->addJoke(new Quote(562, "How many %firstName% %lastName% require to screw a light bulb? None, he will screw it all.", array()));
    $db->addJoke(new Quote(563, "%firstName% %lastName% causes the Windows Blue Screen of Death.", array($nerdy)));
    $db->addJoke(new Quote(564, "%firstName% %lastName% can download emails with his pick-up.", array($nerdy)));
    $db->addJoke(new Quote(565, "%firstName% %lastName% can make a class that is both abstract and final.", array($nerdy)));
    $db->addJoke(new Quote(566, "%firstName% %lastName% could use anything in java.util.* to kill you, including the javadocs.", array($nerdy)));
    $db->addJoke(new Quote(567, "Code runs faster when %firstName% %lastName% watches it.", array($nerdy)));
    $db->addJoke(new Quote(584, "Only %firstName% %lastName% shuts down websites without due process, not SOPA or PIPA.", array()));
    # Number of jokes: 549
  }
}
